### ISSUE TITLE
Permissions not sufficient within private repositories

### ISSUE THREAD

**Issue by chrispader** [Simek/yarn-lock-changes#57] opened 2022-07-12 15:59 UTC
# Problem

Using the example in the `README.md` within private repositories causes the `checkout` job to crash with the following error:
```shell
remote: Repository not found.
Error: fatal: repository 'https://github.com/<your_user>/<your_repo>/' not found
```

This problem is already tracked [here](https://github.com/actions/checkout/issues/254).

# Solution
 
In order to use this action within private repositories, i also needed to add write permissions for `id-token` and read permissions for `contents` to the job, as described [here](https://github.com/actions/checkout/issues/254#issuecomment-981945812), so it looks like something like this:

```yaml
...

yarn_lock_changes:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        id-token: write
        contents: read

...
```

**Comment by klepiz** [comment] 2022-07-14 00:11
Im having exactly the same issue and after override those permissions it still not working :c Im trying to clone an `internal` repo

**Comment by Simek** [comment] 2022-07-14 06:50
Hello guys, thank you for your issues reports and effort put into creating this issue! 👍 

I have tested the action in private repos earlier and it was working for a while, but currently it looks like the actions fails.

Adding the missing permissions, which has been mentioned above and in the `checkout` repo seems to fix an issue to me. I will add an another section to the "Common Issues" section in Readme, however, this is a problem with GitHub owned action, so I cannot do more there.

<img width="937" alt="Screenshot 2022-07-14 084551" src="https://user-images.githubusercontent.com/719641/178919198-2cea18a2-80a6-4a2f-8d18-9b6b9302a9b4.png">

---

@klepiz It's unfortunate to hear that the adding additional permission did not work in your case, but I'm not sure how I can address that. Can you provide more information (maybe there are some custom settings applied?) an d ensure that you are setting the permission in the correct place?

**Comment by Simek** [comment] 2022-07-14 07:24
I'm going to close this issue with the Readme update, since the general approach suggested by @chrispader worked for me.

@klepiz If you still will be experiencing the problems after checking the thing I asked for above, please open new issue with a little bit more details provided, so I can attempt to reproduce the problem. 🙂

**Closed** 2022-07-14 07:24 UTC
